#!/bin/bash

for file in executable-files/*
do 
	name=${file##*/}
	cat $file > /usr/local/sbin/$name
	chmod 755 /usr/local/sbin/$name
done

for file in support-files/*
do
	name=${file##*/}
	cat $file > /usr/local/sbin/$name
done
